In [1]:
l=[1,2,3]

In [2]:
l.append(4)


In [3]:
l

[1, 2, 3, 4]

Test markdown

In [4]:
'''
hello
'''

'\nhello\n'

In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]

In [6]:
my_lists = [my_list1,my_list2]

In [7]:
my_array2 = np.array(my_lists)

In [8]:
my_array2


array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [9]:
my_array2.shape

(2, 4)

In [10]:
my_array2.dtype

dtype('int32')

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
my_zero_array = np.zeros(5)

In [14]:
my_zero_array.dtype

dtype('float64')

In [15]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [1]:
import numpy as np

In [2]:
from __future__ import division

In [3]:
5/2

2.5

In [4]:
arr1 = np.array([[2,3,4,5],[8,9,10,11]])

In [5]:
arr1

array([[ 2,  3,  4,  5],
       [ 8,  9, 10, 11]])

In [6]:
arr1 * arr1

array([[  4,   9,  16,  25],
       [ 64,  81, 100, 121]])

In [7]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
1/ arr1

array([[0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [9]:
arr1 ** 3

array([[   8,   27,   64,  125],
       [ 512,  729, 1000, 1331]], dtype=int32)

In [10]:
import numpy as np

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[8]

8

In [14]:
arr[1:5]

array([1, 2, 3, 4])

In [15]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [16]:
arr[0:5] = 100

In [17]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [19]:
slice_of_arr[:] = 99

In [20]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [21]:
arr_copy = arr.copy()

In [22]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[1]

array([20, 25, 30])

In [26]:
arr_2d[1][0]


20

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
1+1


2

In [29]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [30]:
65+87321

87386

In [32]:
213456789076787864543-878

213456789076787863665

In [33]:
63564332178999999999086431+876421095


63564332179000000875507526

In [34]:
878+86

964

In [35]:
print("Kayna is silly")

Kayna is silly


In [ ]:
print("I am")

In [2]:
import numpy as np

In [3]:
arr = np.arange(50).reshape((10,5))

In [4]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [5]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [6]:
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [7]:
arr3d = np.arange(50).reshape((5,5,2))

In [8]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [10]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [11]:
arr = np.array([1,2,3])

In [12]:
arr

array([1, 2, 3])

In [13]:
arr.swapaxes(0,1)

AxisError: axis2: axis 1 is out of bounds for array of dimension 1

In [14]:
import numpy as np

In [15]:
arr = np.arange(11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [18]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [19]:
A = np.random.random(10)

In [20]:
A

array([0.16141812, 0.52577861, 0.99175779, 0.02238709, 0.19241564,
       0.06612169, 0.74346484, 0.48578231, 0.41028881, 0.3653401 ])

In [21]:
B = np.random.randn(10)

In [22]:
B

array([-1.54209322,  0.37732773, -1.37910563,  0.19306521, -0.24714741,
        0.7538663 , -1.58617502, -0.97806969,  0.96225813, -1.20897806])

In [23]:
np.add(A,B)


array([-1.38067511,  0.90310634, -0.38734784,  0.2154523 , -0.05473177,
        0.81998799, -0.84271017, -0.49228738,  1.37254694, -0.84363796])

In [24]:
np.maximum(A,B)

array([0.16141812, 0.52577861, 0.99175779, 0.19306521, 0.19241564,
       0.7538663 , 0.74346484, 0.48578231, 0.96225813, 0.3653401 ])